// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxN2nl4o56I1U-91JRCa_mHhN-berdeg',
    appId: '1:637535260189:web:a7c2470a0bf60117f5c0f4',
    messagingSenderId: '637535260189',
    projectId: 'schooltrack-7b387',
    authDomain: 'schooltrack-7b387.firebaseapp.com',
    storageBucket: 'schooltrack-7b387.firebasestorage.app',
    measurementId: 'G-HZPXDKFE6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChDv3GXnIgWCrrTLZyHil7AC0PTtzTpfM',
    appId: '1:637535260189:android:a14c4d8a632c5c60f5c0f4',
    messagingSenderId: '637535260189',
    projectId: 'schooltrack-7b387',
    storageBucket: 'schooltrack-7b387.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYig975KzoaDZKUdNQ-vxOPljA_XxVDzc',
    appId: '1:637535260189:ios:ca225b84099b88d3f5c0f4',
    messagingSenderId: '637535260189',
    projectId: 'schooltrack-7b387',
    storageBucket: 'schooltrack-7b387.firebasestorage.app',
    iosClientId: '637535260189-8ue1lnd6fu7c1vrbi43v0ip0qrg49em0.apps.googleusercontent.com',
    iosBundleId: 'com.EduNova.schooltrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYig975KzoaDZKUdNQ-vxOPljA_XxVDzc',
    appId: '1:637535260189:ios:ca225b84099b88d3f5c0f4',
    messagingSenderId: '637535260189',
    projectId: 'schooltrack-7b387',
    storageBucket: 'schooltrack-7b387.firebasestorage.app',
    iosClientId: '637535260189-8ue1lnd6fu7c1vrbi43v0ip0qrg49em0.apps.googleusercontent.com',
    iosBundleId: 'com.EduNova.schooltrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZxN2nl4o56I1U-91JRCa_mHhN-berdeg',
    appId: '1:637535260189:web:c34ed5c843086962f5c0f4',
    messagingSenderId: '637535260189',
    projectId: 'schooltrack-7b387',
    authDomain: 'schooltrack-7b387.firebaseapp.com',
    storageBucket: 'schooltrack-7b387.firebasestorage.app',
    measurementId: 'G-1SSHXCHXY9',
  );
}
